---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html/servicetech.club/site/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R public/* $DEPLOYPATH
    - /bin/cp public/.htaccess $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R includes $DEPLOYPATH
    - /bin/cp -R database $DEPLOYPATH
